### PR TITLE
Small corrections and cleanups

### PR DESCRIPTION
**Pull request by wkrzemien**
Set of changes from several PRs:
1)Remove tinyXml.
2) Add dummy test to travis.
3)Get read of memory leaks
4)small code cleanup

### CODE REVIEW

**Comment by alekgajos** [comment]
I guess something is wrong with the history of this PR as it contains 2 commits which I made over a year ago and which already are in the master branch.

**Comment by wkrzemien** [comment]
I will try to reopen it

**Comment by wkrzemien** [comment]
Closed

**Comment by wkrzemien** [comment]
Im trying to close it, without success :)

**Pull request closed without merging**
