### PR TITLE
Remove tinexml and small cleanups

### PR DESCRIPTION
**Pull request by wkrzemien**
Set of changes from several PRs:
1)Remove tinyXml.
2) Add dummy test to travis.
3)Get read of memory leaks
4)small code cleanup

### CODE REVIEW

**Comment by grey277** [comment]
Doing integration test with j-pet-framework failed, it seems it using same target name "test" as framework:

CMake Error at CMakeLists.txt:184 (add_custom_target):
  add_custom_target cannot create target "tests" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory "/j-pet-framework/Unpacker2/Unpacker2".  See
  documentation for policy CMP0002 for more details.

**Comment by wkrzemien** [comment]
Ok i am going to change it

**Comment by wkrzemien** [comment]
Ok. Dominik will do it :)

**Comment by grey277** [comment]
It seems, there is some another problem, does this PR require some new boost library? Travis tests are passing, but travis is downloading boost from repository: 
/j-pet-framework/Unpacker2/Unpacker2/Unpacker2.cc:8:41: fatal error: boost/property_tree/ptree.hpp: No such file or directory
 #include <boost/property_tree/ptree.hpp>
                                         ^
compilation terminated.
Unpacker2/Unpacker2/CMakeFiles/Unpacker2.dir/build.make:135: recipe for target 'Unpacker2/Unpacker2/CMakeFiles/Unpacker2.dir/Unpacker2.cc.o' failed

Full console output is on jenkins: http://sphinx.if.uj.edu.pl:8080/job/j-pet-framework-PRs-root-5/27/console create account and write me to give you read access if you do not have.

**Pull request merged**
